In [6]:
import pandas as pd

from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer

In [7]:
from Data_laoding_from_excel import load_fish_data

In [8]:
df = load_fish_data("../Data/Raw/Main_Data.xlsx", sheet_name="Data edited")
pd.set_option('display.max_columns', None)
df.head()

,Date,Juilin Date,Month,Day,Year,row,Week,AM Feed,AM Transparency,PM Feed,PM Transparency,Stocked,Spring Temp (F),Max Spring (F),Min Spring (F),Daily turbi mean,Max daily turbi,Max air temp,Min air temp,Dec Rain,Calmar Rain,Year class,Strain,Lot,Sub Lot,Raceway,# fish,Morts,Fish Alive,Fish survival rate,Sub Lot % morts,Lot % mort,Strain % mort,Comments
0,2022-04-22,44673,4,22,2022,477,17,Y,5.450833,X,5.918333,NaN,46.7325,46.94,46.4,6.154271,9.9,64.0,37.0,0.67,0.61,2021,Arlee,ARA2,ARA2A2&A7A2,A2,10023,NaN,10023,100.0,0.0,0.0,0.0,NaN
1,2022-04-22,44673,4,22,2022,477,17,Y,5.450833,X,5.918333,NaN,46.7325,46.94,46.4,6.154271,9.9,64.0,37.0,0.67,0.61,2021,Shasta,STA3,STA3A3,A3,10010,NaN,10010,100.0,0.0,0.0,0.0,NaN
2,2022-04-22,44673,4,22,2022,477,17,Y,5.450833,X,5.918333,NaN,46.7325,46.94,46.4,6.154271,9.9,64.0,37.0,0.67,0.61,2021,Shasta,STA4,STA4A4,A4,10385,NaN,10385,100.0,0.0,0.0,0.0,NaN
3,2022-04-22,44673,4,22,2022,477,17,Y,5.450833,X,5.918333,NaN,46.7325,46.94,46.4,6.154271,9.9,64.0,37.0,0.67,0.61,2021,Shasta,STA4,STA4A5,A5,10595,NaN,10595,100.0,0.0,0.0,0.0,NaN
4,2022-04-22,44673,4,22,2022,477,17,Y,5.450833,X,5.918333,NaN,46.7325,46.94,46.4,6.154271,9.9,64.0,37.0,0.67,0.61,2021,Shasta,STA6,STA6A6,A6,7806,NaN,7806,100.0,0.0,0.0,0.0,NaN

In [11]:
selected_columns = ["Date", "Month","Day", "Year", "AM Feed", "AM Transparency", "PM Feed", "PM Transparency","Stocked", "Spring Temp (F)", "Morts", "# fish", "Dec Rain", "Calmar Rain", "Strain", "Lot", "Sub Lot", "Raceway", "# fish","Morts", "Fish Alive", "Fish survival rate"]
new_df = df[selected_columns]
new_df.head()

,Date,Month,Day,Year,AM Feed,AM Transparency,PM Feed,PM Transparency,Stocked,Spring Temp (F),Morts,# fish,Dec Rain,Calmar Rain,Strain,Lot,Sub Lot,Raceway,# fish,Morts,Fish Alive,Fish survival rate
0,2022-04-22,4,22,2022,Y,5.450833,X,5.918333,NaN,46.7325,NaN,10023,0.67,0.61,Arlee,ARA2,ARA2A2&A7A2,A2,10023,NaN,10023,100.0
1,2022-04-22,4,22,2022,Y,5.450833,X,5.918333,NaN,46.7325,NaN,10010,0.67,0.61,Shasta,STA3,STA3A3,A3,10010,NaN,10010,100.0
2,2022-04-22,4,22,2022,Y,5.450833,X,5.918333,NaN,46.7325,NaN,10385,0.67,0.61,Shasta,STA4,STA4A4,A4,10385,NaN,10385,100.0
3,2022-04-22,4,22,2022,Y,5.450833,X,5.918333,NaN,46.7325,NaN,10595,0.67,0.61,Shasta,STA4,STA4A5,A5,10595,NaN,10595,100.0
4,2022-04-22,4,22,2022,Y,5.450833,X,5.918333,NaN,46.7325,NaN,7806,0.67,0.61,Shasta,STA6,STA6A6,A6,7806,NaN,7806,100.0

### Y will be Fish Survival Rate (%) = Formula: (fish alive / # fish) * 100
### X will be the other values in the new_df. You can add or remove some valeus if you like.